### PR TITLE
Use late final directly - no need for getters

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by natebosch** [comment]
A `late final` is still statically assignable outside the class, we don't want that.

**Comment by kevmoo** [comment]
> A `late final` is still statically assignable outside the class, we don't want that.

But you cannot get the instance without going through the ctor which assigns it – right?

**Comment by natebosch** [comment]
Yes, the setter would throw. We'd prefer to keep it out of the API entirely than to introduce a setter that is guaranteed to throw.

cc @leafpetersen - was there ever a discussion about whether a `late final` instance field could statically hide it's setter outside the class?

**Comment by kevmoo** [comment]
oh...hrm...okay.

**Comment by kevmoo** [comment]
I never considered the case of a `late final` being assigned outside of the declaring class. Good point!

**Comment by leafpetersen** [comment]
> cc @leafpetersen - was there ever a discussion about whether a `late final` instance field could statically hide it's setter outside the class?

I don't know that we ever explicitly discussed it, no.  You could file a language issue to discuss it.  My initial take is that:
 - We don't want to always make it hidden 
 - We don't have any existing mechanism for marking it as hidden or not
 - You can make the late final variable library private with a public getter, and it/when we add private/protected you could do the same.

**Comment by kevmoo** [comment]
> * We don't want to always make it hidden
> * We don't have any existing mechanism for marking it as hidden or not
> * You can make the late final variable library private with a public getter, and it/when we add private/protected you could do the same.

2 things I hated about late-assigned local vars

1) the fact that there is nothing stopping one from re-assigning
2) the fact we had to hide it with a getter.

I was pushing to solve both with `late` – but I'll live if we only solve the first 😄

**Comment by kevmoo** [comment]
closing this out!

**Pull request closed without merging**
